version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres-jwt
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: jwt_security
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
volumes:
  postgres_volume:
